"""Public Sunofriend command registry shared by CLI, TUI and skill checks."""

from __future__ import annotations

from itertools import chain

from .product_contract import product_contract_document


INTERFACE_CONTRACT_VERSION = "2026-07-27.4"

# Categories describe discoverability only. They do not grant authority, merge
# workflows or weaken the individual command contracts.
PUBLIC_COMMAND_GROUPS: dict[str, tuple[str, ...]] = {
    "start_and_setup": (
        "tui",
        "doctor",
        "ai-doctor",
        "garageband-info",
        "instrument-inventory",
        "midi-ports",
    ),
    "transcribe_and_generate": (
        "remake",
        "listen",
        "listen-all",
        "vocal-melody",
        "vocal-trackers",
        "ai-transcribe",
        "ai-transcribe-session",
        "ai-cleanup",
        "midi-mask",
    ),
    "compare_and_review": (
        "evaluate",
        "melody-review",
        "melody-profile",
        "melody-guide",
        "melody-apply",
        "ai-benchmark",
        "ai-setting-compare",
        "ai-cache-benchmark",
        "ai-session-benchmark",
        "ai-matrix",
        "hybrid-report",
        "ai-label-split",
        "midi-role-split",
        "midi-role-split-resolve",
        "midi-ab-review",
        "midi-ab-resolve",
        "timbre-resynthesis",
        "listening-master",
        "workbench",
        "garageband-pack-review",
        "garageband-pack-resolve",
    ),
    "transform_and_play": (
        "preview",
        "play",
        "midi-tempo",
        "midi-transform",
        "midi-anchor",
        "midi-align",
    ),
    "instruments": (
        "instrument-match",
        "sample-pack",
        "sample-pack-review",
        "sample-pack-apply",
        "sample-pack-boundary-review",
        "sample-pack-boundary-apply",
        "sample-pack-ab-review",
        "sample-pack-ab-resolve",
        "instrument-feedback",
        "instrument-profile",
        "instrument-bundle",
    ),
    "clip_library": (
        "clip-import",
        "clip-list",
        "clip-show",
        "clip-export",
        "clip-transform",
        "clip-instrument",
    ),
}

PUBLIC_COMMANDS = frozenset(chain.from_iterable(PUBLIC_COMMAND_GROUPS.values()))

# The Guided Local Studio has typed full-project conversion plus exact-current
# Listening Master orchestration over the existing production services. Every
# other public command remains available through the CLI and is planned for
# later typed TUI operation forms rather than being hidden or falsely
# described as complete.
DIRECT_TUI_COMMANDS = frozenset(
    {
        "tui",
        "doctor",
        "listen-all",
        "vocal-melody",
        "listening-master",
        "workbench",
    }
)

_GROUP_TITLES = {
    "start_and_setup": "Start and setup",
    "transcribe_and_generate": "Transcribe and generate",
    "compare_and_review": "Compare and review",
    "transform_and_play": "Transform and play",
    "instruments": "Instruments",
    "clip_library": "Clip library",
}


def command_category(command: str) -> str:
    """Return the stable discovery category for one public command."""

    for category, commands in PUBLIC_COMMAND_GROUPS.items():
        if command in commands:
            return category
    raise ValueError(f"unknown public Sunofriend command: {command}")


def render_skill_interface_reference() -> str:
    """Render the checked-in skill command reference from the public registry."""

    lines = [
        "# Sunofriend interface contract",
        "",
        "<!-- Generated by sunofriend.interface_contract; do not edit by hand. -->",
        "",
        f"Contract version: `{INTERFACE_CONTRACT_VERSION}`",
        "",
        "The Guided Local Studio TUI is the preferred human entry point. The",
        "expert CLI and agent skill remain supported and share the public",
        "commands below.",
        "",
        "## Product outputs",
        "",
        "Sunofriend produces two linked creative outputs:",
        "",
    ]
    product = product_contract_document()
    lines.extend(
        f"- **{output['label']}** (`{output['output_id']}`)"
        for output in product["required_outputs"]
    )
    lines.extend(
        [
            "",
            "The song-interpretation WAV is rendered only from explicitly",
            "selected MIDI. Source stems provide timing, render-horizon and",
            "level evidence but are not mixed into it. Interpolation means a",
            "creative MIDI interpretation, not waveform reconstruction.",
            "",
            "The optional listening master is a comparative artifact, not a",
            "human-approved release master. Playback, metrics and visible",
            "defaults never imply a preference.",
            "",
            "Ordinary Workbench and the Guided Local Studio Master tab can",
            "explicitly build or reuse a separate fixed-policy",
            "listening-master challenger from the exact current balanced",
            "control. The gain-only control remains unchanged; the operation",
            "records no feedback or preference and changes no MIDI, selection,",
            "default or GarageBand pack. Blinded control-versus-challenger",
            "feedback remains deferred.",
            "",
            "## Guided entry points",
            "",
            "Direct guided TUI actions in the current increment:",
            "",
        ]
    )
    lines.extend(f"- `sunofriend {command}`" for command in sorted(DIRECT_TUI_COMMANDS))
    lines.extend(
        [
            "",
            "Every other command remains available through the expert CLI while",
            "typed TUI operation forms are added incrementally.",
            "",
        ]
    )
    for group, commands in PUBLIC_COMMAND_GROUPS.items():
        lines.extend(
            [
                f"## {_GROUP_TITLES[group]}",
                "",
                *(f"- `sunofriend {command}`" for command in commands),
                "",
            ]
        )
    return "\n".join(lines)


__all__ = [
    "DIRECT_TUI_COMMANDS",
    "INTERFACE_CONTRACT_VERSION",
    "PUBLIC_COMMAND_GROUPS",
    "PUBLIC_COMMANDS",
    "command_category",
    "render_skill_interface_reference",
]
