"""Public Sunofriend command registry shared by CLI, TUI and skill checks."""

from __future__ import annotations

from itertools import chain

from .product_contract import product_contract_document


INTERFACE_CONTRACT_VERSION = "2026-08-06.11"

# Categories describe discoverability only. They do not grant authority, merge
# workflows or weaken the individual command contracts.
PUBLIC_COMMAND_GROUPS: dict[str, tuple[str, ...]] = {
    "start_and_setup": (
        "create",
        "demo",
        "tui",
        "doctor",
        "source-doctor",
        "source-import",
        "source-import-folder",
        "ai-doctor",
        "garageband-info",
        "instrument-inventory",
        "midi-ports",
    ),
    "transcribe_and_generate": (
        "remake",
        "listen",
        "listen-all",
        "vocal-melody",
        "vocal-trackers",
        "ai-transcribe",
        "ai-transcribe-session",
        "ai-cleanup",
        "midi-mask",
    ),
    "compare_and_review": (
        "evaluate",
        "melody-review",
        "melody-profile",
        "melody-guide",
        "melody-apply",
        "ai-benchmark",
        "ai-setting-compare",
        "ai-cache-benchmark",
        "ai-session-benchmark",
        "ai-matrix",
        "hybrid-report",
        "ai-label-split",
        "midi-role-split",
        "midi-role-split-resolve",
        "midi-ab-review",
        "midi-ab-status",
        "midi-ab-resolve",
        "timbre-resynthesis",
        "listening-master",
        "workbench",
        "garageband-pack-review",
        "garageband-pack-resolve",
    ),
    "transform_and_play": (
        "preview",
        "play",
        "midi-tempo",
        "midi-transform",
        "midi-anchor",
        "midi-align",
    ),
    "instruments": (
        "instrument-match",
        "sample-pack",
        "sample-pack-review",
        "sample-pack-apply",
        "sample-pack-boundary-review",
        "sample-pack-boundary-apply",
        "sample-pack-ab-review",
        "sample-pack-ab-resolve",
        "instrument-feedback",
        "instrument-profile",
        "instrument-bundle",
    ),
    "clip_library": (
        "clip-import",
        "clip-list",
        "clip-show",
        "clip-export",
        "clip-transform",
        "clip-instrument",
    ),
}

PUBLIC_COMMANDS = frozenset(chain.from_iterable(PUBLIC_COMMAND_GROUPS.values()))

# The Guided Local Studio has typed full-project conversion plus exact-current
# Listening Master orchestration over the existing production services. Every
# other public command remains available through the CLI and is planned for
# later typed TUI operation forms rather than being hidden or falsely
# described as complete.
DIRECT_TUI_COMMANDS = frozenset(
    {
        "tui",
        "doctor",
        "listen-all",
        "vocal-melody",
        "listening-master",
        "workbench",
    }
)

_GROUP_TITLES = {
    "start_and_setup": "Start and setup",
    "transcribe_and_generate": "Transcribe and generate",
    "compare_and_review": "Compare and review",
    "transform_and_play": "Transform and play",
    "instruments": "Instruments",
    "clip_library": "Clip library",
}


def command_category(command: str) -> str:
    """Return the stable discovery category for one public command."""

    for category, commands in PUBLIC_COMMAND_GROUPS.items():
        if command in commands:
            return category
    raise ValueError(f"unknown public Sunofriend command: {command}")


def render_skill_interface_reference() -> str:
    """Render the checked-in skill command reference from the public registry."""

    lines = [
        "# Sunofriend interface contract",
        "",
        "<!-- Generated by sunofriend.interface_contract; do not edit by hand. -->",
        "",
        f"Contract version: `{INTERFACE_CONTRACT_VERSION}`",
        "",
        "The Guided Local Studio TUI is the preferred human entry point. It",
        "opens in Simple mode by default; `sunofriend tui --mode studio` opens",
        "the detailed comparison workspace first. Its visible Simple/Studio",
        "switch changes views in either direction and remembers the last",
        "Studio tab without starting work or changing project state. The",
        "expert CLI and agent skill",
        "remain supported and share the public commands below.",
        "",
        "## Source preparation",
        "",
        "`sunofriend source-doctor` inspects an existing local FFmpeg/FFprobe",
        "toolchain without writing files.",
        "",
        "`sunofriend source-import` preserves exactly one authorised local",
        "audio asset as immutable original evidence plus canonical PCM24 WAV.",
        "It does not create stems or make a complete Simple/Studio project.",
        "",
        "`sunofriend source-import-folder` prepares 2–64 already-separated,",
        "synchronized top-level audio parts as one fresh canonical WAV stem",
        "project. Plan mode is read-only. Execution never separates, shifts,",
        "pads, stretches, normalizes or musically aligns audio. Compatible",
        "recorded origins are evidence, not proof of a downbeat or musical",
        "alignment.",
        "",
        "`sunofriend create` and TUI Simple/Studio consume a prepared project",
        "of synchronized top-level WAV stems to make MIDI, a MIDI-derived",
        "song-interpretation WAV and a GarageBand handoff. Preparing a folder",
        "and converting it are separate actions.",
        "",
        "The separate `sunofriend-separate` entry point estimates stems from",
        "one authorised finished mix on a supported Apple-silicon Mac. Broad",
        "vocals plus complementary instrumental remains the default. The",
        "immutable SCNet-large profile is now a public opt-in preview for vocals,",
        "drums, bass and grouped other. Its exact runtime, checkpoint and source",
        "identity passed compatibility and inference checks under network denial.",
        "A copyright-safe synthetic canary, three authorised song-disjoint canaries",
        "and three repeat resource runs passed the objective gates; the project owner",
        "reported no catastrophic defect after listening to every full-song output.",
        "The first verified machine class is a 36 GB M3 Max. Other Apple-silicon",
        "classes, including 16 GiB machines, remain accessible but unverified and",
        "resource-supervised. The earlier MLX baseline and PyTorch fallback remain",
        "blocked after their bounded objective remediations failed.",
        "Results are local, experimental and unreviewed for musical usefulness.",
        "No separated output enters MIDI conversion automatically.",
        "`sunofriend-separate profiles` exposes exact status. Blocked profiles",
        "cannot run. Poor musical feedback is valid",
        "evidence, not an admission veto or an unlimited tuning trigger.",
        "A separate `other-refinement-v1` contract is registered for Studio-only",
        "research. It binds one exact grouped-other parent to one requested guitar",
        "or keys target plus an exact PCM24 residual. The parent and children are",
        "mutually exclusive for activation and MIDI. Its first backend candidate is the",
        "exact blocked `demucs-mlx-htdemucs-6s-other-refinement-v1`; guitar maps to the",
        "model guitar role and keys is a disclosed piano proxy. Registration installs",
        "or runs no model, exposes no refinement command and remains blocked until the",
        "separately approved setup, fraction-normalized loader and objective gates pass.",
        "No Sunofriend command downloads music.",
        "",
        "## Product outputs",
        "",
        "Sunofriend produces two linked creative outputs:",
        "",
    ]
    product = product_contract_document()
    lines.extend(
        f"- **{output['label']}** (`{output['output_id']}`)"
        for output in product["required_outputs"]
    )
    simple = product["modes"]["simple"]
    studio = product["modes"]["studio"]
    lines.extend(
        [
            "",
            "### Two honest operating modes",
            "",
            f"- **Simple / Make my song:** {simple['result_kind']}. It uses",
            "  exact production-summary primaries, is marked automatic and",
            "  unreviewed, writes no human decision or feedback event, and",
            "  recommends Studio review.",
            "  It also publishes separately labelled starter-sound MIDI, named",
            "  General MIDI assignments, short per-part previews and a GarageBand",
            "  instrument guide while leaving every automatic-primary MIDI exact.",
            f"- **Studio:** {studio['result_kind']}. Choices and feedback are",
            "  recorded only after an explicit human action.",
            "",
            "The song-interpretation WAV is rendered only from explicitly",
            "selected MIDI in Studio or separately labelled automatic-primary",
            "MIDI in Simple mode. Source stems provide timing, render-horizon",
            "and level evidence but are not mixed into it. Interpolation means",
            "a creative MIDI interpretation, not waveform reconstruction.",
            "",
            "The optional listening master is a comparative artifact, not a",
            "human-approved release master. Playback, metrics and visible",
            "defaults never imply a preference.",
            "",
            "Ordinary Workbench and the Guided Local Studio Master tab can",
            "explicitly build or reuse a separate fixed-policy",
            "listening-master challenger from the exact current balanced",
            "control. The gain-only control remains unchanged; the operation",
            "records no feedback or preference and changes no MIDI, selection,",
            "default or GarageBand pack.",
            "",
            "Workbench can then prepare one exact 0.5–15 second blinded,",
            "fixed-window sample-RMS-matched control-versus-challenger review.",
            "Only explicit completion records a separate local feedback",
            "artifact; a second explicit action reveals the A/B assignment.",
            "Neither action promotes an artifact or changes MIDI, selection,",
            "ranking, product completion, defaults or the GarageBand pack.",
            "",
            "## Guided entry points",
            "",
            "Direct guided TUI actions in the current increment:",
            "",
        ]
    )
    lines.extend(f"- `sunofriend {command}`" for command in sorted(DIRECT_TUI_COMMANDS))
    lines.extend(
        [
            "",
            "Every other command remains available through the expert CLI while",
            "typed TUI operation forms are added incrementally.",
            "",
        ]
    )
    for group, commands in PUBLIC_COMMAND_GROUPS.items():
        lines.extend(
            [
                f"## {_GROUP_TITLES[group]}",
                "",
                *(f"- `sunofriend {command}`" for command in commands),
                "",
            ]
        )
    return "\n".join(lines)


__all__ = [
    "DIRECT_TUI_COMMANDS",
    "INTERFACE_CONTRACT_VERSION",
    "PUBLIC_COMMAND_GROUPS",
    "PUBLIC_COMMANDS",
    "command_category",
    "render_skill_interface_reference",
]
