const query=new URLSearchParams(location.search);const token=query.get("token")||"";const withToken=path=>`${path}${path.includes("?")?"&":"?"}token=${encodeURIComponent(token)}`;const api=async(path,options={})=>{const response=await fetch(withToken(path),options);const value=await response.json();if(!response.ok)throw new Error(value.error||`Request failed (${response.status})`);return value};
const labels={motif:"Repeating hook or motif",bass_movement:"Bass movement",harmonic_event:"Harmony or chord movement",groove:"Groove or rhythmic feel",structural_relationship:"Section shape or musical relationship"};
let state=null;const player=document.getElementById("player");const status=document.getElementById("status");
const setStatus=(message,kind="")=>{status.textContent=message;status.className=kind};
const play=async name=>{const media=state.media[name];player.pause();player.src=media.media_url;player.load();await new Promise((resolve,reject)=>{if(player.readyState>=1){resolve();return}player.addEventListener("loadedmetadata",resolve,{once:true});player.addEventListener("error",()=>reject(new Error("Audio could not be loaded")),{once:true})});await player.play()};
document.querySelectorAll("[data-play]").forEach(button=>button.addEventListener("click",()=>play(button.dataset.play).catch(error=>setStatus(error.message,"error"))));document.getElementById("stop").addEventListener("click",()=>{player.pause();player.currentTime=0});
const initialize=async()=>{state=await api("/api/session");document.getElementById("title").textContent=state.title;document.getElementById("duration").textContent=`Available clock: 0.000 to ${state.clock.duration_seconds.toFixed(3)} seconds.`;const select=document.getElementById("anchor-kind");select.innerHTML='<option value="">Choose the musical relationship…</option>'+state.anchor_kinds.map(value=>`<option value="${value}">${labels[value]||value}</option>`).join("");if(state.saved_confirmation){document.getElementById("confirm").disabled=true;setStatus("Musical anchor already confirmed locally.","saved")}};
document.getElementById("confirm").addEventListener("click",async()=>{setStatus("");const rate=state.clock.sample_rate_hz;const start=Number(document.getElementById("start-seconds").value);const end=Number(document.getElementById("end-seconds").value);if(!Number.isFinite(start)||!Number.isFinite(end)){setStatus("Enter the exact start and end of the musical anchor.","error");return}const payload={expected_project_state_sha256:state.project_state.document_sha256,explicitly_heard:{source_control:document.getElementById("heard-source").checked,separation_estimate:document.getElementById("heard-estimate").checked},owner_label:document.getElementById("owner-label").value,anchor_kind:document.getElementById("anchor-kind").value,start_frame:Math.round(start*rate),end_frame:Math.round(end*rate),preservation_requirement:state.preservation_requirement};try{const result=await api("/api/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});state=result.state;document.getElementById("confirm").disabled=true;setStatus("Musical anchor saved locally. Controlled variants can now be prepared separately.","saved")}catch(error){setStatus(error.message,"error")}});
initialize().catch(error=>setStatus(error.message,"error"));
